Xây dựng, tối ưu hóa siêu tham số và so sánh hai mô hình học máy (Decision Tree và Random Forest) dựa trên bộ dữ liệu heart.csv để phân loại (chẩn đoán) việc bệnh nhân CÓ hay KHÔNG mắc bệnh tim.

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report , confusion_matrix
from sklearn.ensemble import RandomForestClassifier

df = pd.read_csv('heart.csv')
display(df.head())
df = df.drop_duplicates()

X = df.drop(columns = 'target')
Y = df['target']

X_train, X_test, Y_train, Y_test = train_test_split(X, Y , test_size = 0.2, random_state=42)

clf_full = DecisionTreeClassifier(random_state=42)
path = clf_full.cost_complexity_pruning_path(X_train,Y_train)
alphas = path.ccp_alphas[:-1]

grid_search = GridSearchCV(
    estimator = DecisionTreeClassifier(random_state=42),
    param_grid = {'ccp_alpha': alphas},
    cv = 10,
    scoring = 'recall'
)

grid_search.fit(X_train, Y_train)


best_alpha = grid_search.best_params_['ccp_alpha']
best_tree = grid_search.best_estimator_


Y_pred = best_tree.predict(X_test)

print(confusion_matrix(Y_test,Y_pred))
print(classification_report(Y_test,Y_pred))


rf_gridsearch = GridSearchCV(
    estimator = RandomForestClassifier(random_state = 42),
    param_grid = {'n_estimators' : [50, 100, 200],
                  'max_depth' : [None, 5, 7]
                  },
    cv = 10,
    scoring = 'recall'
)

best_forest = rf_gridsearch.fit(X_train, Y_train)

Y_pred_rf = best_forest.predict(X_test)
print(confusion_matrix(Y_test,Y_pred_rf))
print(classification_report(Y_test,Y_pred_rf))

   age  sex  cp  trestbps  chol  fbs  ...  exang  oldpeak  slope  ca  thal  target
0   52    1   0       125   212    0  ...      0      1.0      2   2     3       0
1   53    1   0       140   203    1  ...      1      3.1      0   0     3       0
2   70    1   0       145   174    0  ...      1      2.6      0   0     3       0
3   61    1   0       148   203    0  ...      0      0.0      2   1     3       0
4   62    0   0       138   294    1  ...      0      1.9      1   3     2       0

[5 rows x 14 columns]

[[25  7]
 [ 8 21]]
              precision    recall  f1-score   support

           0       0.76      0.78      0.77        32
           1       0.75      0.72      0.74        29

    accuracy                           0.75        61
   macro avg       0.75      0.75      0.75        61
weighted avg       0.75      0.75      0.75        61

[[25  7]
 [ 3 26]]
              precision    recall  f1-score   support

           0       0.89      0.78      0.83        32
           1       0.79      0.90      0.84        29

    accuracy                           0.84        61
   macro avg       0.84      0.84      0.84        61
weighted avg       0.84      0.84      0.84        61

Xây dựng, tiền xử lý dữ liệu, tối ưu hóa siêu tham số và so sánh hiệu suất của hai mô hình học máy (Decision Tree Regressor và Random Forest Regressor) dựa trên bộ dữ liệu train.csv để dự đoán giá bán nhà (SalePrice). Tiêu chí đánh giá và tối ưu chính là hệ số xác định $R^2$ (R-squared).

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import r2_score
from sklearn.ensemble import RandomForestRegressor

df = pd.read_csv('train.csv')
df = df.drop_duplicates()
display(df.head())

num_cols = df.select_dtypes(include = ['int64','float64']).columns
df[num_cols] = df[num_cols].fillna(df[num_cols].mean())

cat_cols = df.select_dtypes(include = ['object']).columns
df[cat_cols] = df[cat_cols].fillna('Missing')

df = pd.get_dummies(df, drop_first = True)
X = df.drop(columns = ['Id', 'SalePrice'])
Y = df['SalePrice']

X_train, X_test , Y_train, Y_test = train_test_split(X,Y, test_size=0.2, random_state= 42)

clf_full = DecisionTreeRegressor(random_state=42)
path = clf_full.cost_complexity_pruning_path(X_train, Y_train)
alphas = path.ccp_alphas[:10]

grid_search = GridSearchCV(
    estimator = DecisionTreeRegressor(),
    param_grid = {'ccp_alpha' : alphas},
    cv = 5,
    scoring = 'r2'
)

grid_search.fit(X_train, Y_train)

best_tree = grid_search.best_estimator_

Y_pred = best_tree.predict(X_test)
r2 = r2_score(Y_test, Y_pred)

rf_grid = GridSearchCV(
    estimator = RandomForestRegressor(random_state=42),
    param_grid = {
        'n_estimators': [50, 100],
        'max_depth': [5, 10,None]
    },
    cv = 5,
    scoring = 'r2',
)
rf_grid.fit(X_train, Y_train)
Y_pred_rf = rf_grid.predict(X_test)

r2_rf = r2_score(Y_test, Y_pred_rf)

print("R2 của Cây quyết định:", r2)
print("R2 của Random Forest:", r2_rf)
print("Cấu hình RF tốt nhất máy tìm được:", rf_grid.best_params_)

   Id  MSSubClass MSZoning  ...  SaleType  SaleCondition SalePrice
0   1          60       RL  ...        WD         Normal    208500
1   2          20       RL  ...        WD         Normal    181500
2   3          60       RL  ...        WD         Normal    223500
3   4          70       RL  ...        WD        Abnorml    140000
4   5          60       RL  ...        WD         Normal    250000

[5 rows x 81 columns]

R2 của Cây quyết định: 0.7310411972933102
R2 của Random Forest: 0.8908490635721261
Cấu hình RF tốt nhất máy tìm được: {'max_depth': 10, 'n_estimators': 100}